# Generated by Django 3.1.5 on 2021-01-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='rel',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
